name: note_app
description: "A Flutter note-taking app with CI/CD pipeline"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  http: ^1.1.0
  # Add image support
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  path_provider: ^2.1.1
  audioplayers: ^6.0.0
  file_picker: ^9.0.0
  path: ^1.8.3
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.9
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/databases/comprehensive_search.db