// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAp0_kZpur9q6BN6bJ_FCeGhVvCJsc7Yuc',
    appId: '1:336403606227:web:3791c49f8e00a8f8c60226',
    messagingSenderId: '336403606227',
    projectId: 'cross-platform-mid',
    authDomain: 'cross-platform-mid.firebaseapp.com',
    storageBucket: 'cross-platform-mid.firebasestorage.app',
    measurementId: 'G-XWB9KR431M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXukwz3ld7YZWLzL7AaX-W7RMh72Bt3Aw',
    appId: '1:336403606227:android:5797feac58e4ae9cc60226',
    messagingSenderId: '336403606227',
    projectId: 'cross-platform-mid',
    storageBucket: 'cross-platform-mid.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn-BvEsUDD9Q9lBYTQGGhxMzfNuH2tBfg',
    appId: '1:336403606227:ios:06a57fa5e7b93078c60226',
    messagingSenderId: '336403606227',
    projectId: 'cross-platform-mid',
    storageBucket: 'cross-platform-mid.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn-BvEsUDD9Q9lBYTQGGhxMzfNuH2tBfg',
    appId: '1:336403606227:ios:06a57fa5e7b93078c60226',
    messagingSenderId: '336403606227',
    projectId: 'cross-platform-mid',
    storageBucket: 'cross-platform-mid.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAp0_kZpur9q6BN6bJ_FCeGhVvCJsc7Yuc',
    appId: '1:336403606227:web:e2a5de335387d47ac60226',
    messagingSenderId: '336403606227',
    projectId: 'cross-platform-mid',
    authDomain: 'cross-platform-mid.firebaseapp.com',
    storageBucket: 'cross-platform-mid.firebasestorage.app',
    measurementId: 'G-SXG0GT0HBF',
  );
}
